name: Exec code

on:
  push:
    branches:
        - 'master'

jobs:
  exec_code:
    runs-on: ubuntu-latest
    name: Exec-Code-Job

    steps:
      - uses: actions/checkout@v2
      - name: code execution
        uses: sanix-darker/d-exe-action@v1
