name: Exec code

on:
  push:
    branches:
        - 'master'

jobs:
    exec_code:
        runs-on: ubuntu-latest
        name: exec-code

        steps:
            - uses: actions/checkout@v2

            - name: get code and runtime
              id: vars
              run: |
                lv="python=3.9.4"
                langVersion=(${lv//=/ })
                lang=${langVersion[0]}
                version=${langVersion[1]}

                code=$(cat ./code)

                echo "===---===---==="
                echo $code
                echo "===---===---==="

                curl -s -L -X POST "http://147.182.205.116:4321/api/v1/execute" \
                -H "Content-Type: application/json" \
                -d '{
                    "name": "test",
                    "lang": "'$lang'",
                    "version": "'$version'",
                    "code": "print(\"Hello work !\")",
                    "stdin": ""
                }' | \
                jq '. | {out: .run.stdout, err: .run.stderr}' | \
                jq -r '[.out, .err] | @tsv' | \
                while IFS=$'\t' read -r out err; do
                    echo "-------"
                    echo $out > ./out
                    echo $err > ./err
                    echo "-------"
                    cat ./out
                    # echo ::set-output name=SIGNAL::$(echo $signal)
                done
              shell: bash

            - name: Commit files
              run: |
                git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
                git config --local user.name "github-actions[bot]"
                git commit -m "exe: code executed" -a

            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                github_token: ${{ secrets.GH_TOKEN }}
                branch: ${{ github.ref }}
