name: Exec code

on:
  push:
    branches:
        - 'master'

jobs:
  exec_code:
    runs-on: ubuntu-latest
    name: Exec-Code-Job

    steps:
        - uses: actions/checkout@v2

        - name: code & runtime
          run: ./exec.sh
          shell: bash

        - name: commit changes
          run: ./commit.sh
          shell: bash

        - name: push updates
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GH_TOKEN }}
            branch: ${{ github.ref }}
