name: Exec code

on:
  push:
    branches:
        - 'master'

jobs:
  exec_code:
    runs-on: ubuntu-latest
    name: Exec-Code-Job

    steps:
      - uses: actions/checkout@v2

      - id: execution
        uses: sanix-darker/d-exe-action@master
        with:
          code: $(cat ${GITHUB_WORKSPACE}/code)
          langVersion: $(cat ${GITHUB_WORKSPACE}/langVersion)
      
      - name: get code result
        run: |
          printf "stdout: \n${{ steps.execution.outputs.stdout}}"
          printf "stderr: \n${{ steps.execution.outputs.stderr}}"
          printf "output: \n${{ steps.execution.outputs.output}}"
          printf "signal: \n${{ steps.execution.outputs.signal}}"

