name: Exec code

on:
  push:
    branches:
        - 'master'

jobs:
  exec_code:
    runs-on: ubuntu-latest
    name: Exec-Code-Job

    steps:
      - uses: actions/checkout@v2

      - name: get code and runtime
        id: vars
        run: |
            echo ::set-output name=code::$(cat ${GITHUB_WORKSPACE}/code)
            echo ::set-output name=langVersion::$(cat ${GITHUB_WORKSPACE}/langVersion)

      - id: execution
        uses: sanix-darker/d-exe-action@v1
        with:
          code: ${{ steps.vars.outputs.code }}
          langVersion: ${{ steps.vars.outputs.langVersion }}
      
      - name: get code result
        run: |
          cat ${GITHUB_WORKSPACE}/outout
